version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:      
      - echo Pre Build started on `date`
      #TODO: Login CodeArtifact      
  build:
    commands:
      - echo Build started on `date`
      - mvn package
  post_build:    
    commands:
      - echo Post Build completed on `date`
      #TODO: mvn deploy to CodeArtifact      
artifacts:
  files:
    #- target/sample-*.jar
cache:
  paths:
    - '/root/.m2/**/*'
