AWSTemplateFormatVersion: 2010-09-09
Description: IAM Template for CloudFormation Demo. 
#Metadata: 

Parameters: 
  StackPrefix:
    Description: Stack Resource Name Prefix
    Type: String
    Default: Demo
  CodeBuildProjectName:
    Description: Frontend CodeBuild Project Name
    Type: String
    Default: demo-fw-ci    
  CodeCommitRepositoryName:
    Description: Source Code Repository Location of CodeCommit
    Type: String
    Default: sample-fw
  ArtifactS3BucketName:
    Description: Artifact Location of S3 Bucket
    Type: String
    Default: mysd33bucket123
  CacheS3Location:
    Description: Artifact Location of S3 Bucket Name/Prefix
    Type: String
    Default: mysd33bucket123/cache    

#Mappings: 

#Conditions: 

Resources:
  #IAM Role and IAM Policy for CodeBuild
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /service-role/
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - 'sts:AssumeRole'  
  #TODO: Review IAM Policy  
  CodeBuildPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
        - Action:
          - logs:CreateLogGroup
          - logs:CreateLogStream
          - logs:PutLogEvents
          Effect: Allow
          Resource:
          - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${CodeBuildProjectName}
          - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${CodeBuildProjectName}:*          
        - Action:
          - codecommit:GitPull
          Effect: Allow
          Resource:          
            - !Sub arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:${CodeCommitRepositoryName}    
        - Action:
          - s3:PutObject
          - s3:GetObject
          - s3:GetObjectVersion
          - s3:GetBucketAcl
          - s3:GetBucketLocation
          Effect: Allow
          Resource: 
            - !Sub arn:aws:s3:::${ArtifactS3BucketName}
            - !Sub arn:aws:s3:::${ArtifactS3BucketName}/*      
            - !Sub arn:aws:s3:::${CacheS3Location}            
            - !Sub arn:aws:s3:::${CacheS3Location}/*
        - Action:
          - codeartifact:List*
          - codeartifact:Describe*
          - codeartifact:Get*
          - codeartifact:Read*
          - codeartifact:PublishPackageVersion          
          - codeartifact:PutPackageMetadata
          Effect: Allow
          Resource: 
            - !Sub arn:aws:codeartifact:${AWS::Region}:${AWS::AccountId}:domain/*
            - !Sub arn:aws:codeartifact:${AWS::Region}:${AWS::AccountId}:repository/*
            - !Sub arn:aws:codeartifact:${AWS::Region}:${AWS::AccountId}:package/*
        - Action:
          - sts:GetServiceBearerToken
          Effect: Allow
          Resource:
            - "*"
          Condition:
            StringEquals:
              'sts:AWSServiceName': codeartifact.amazonaws.com
      PolicyName: !Sub ${StackPrefix}-CodeBuildPolicy
      Roles:
      - !Ref CodeBuildRole

Outputs:
  CodeBuildRoleArn:
    Description: CodeBuildRole Arn
    Value: !GetAtt CodeBuildRole.Arn
    Export: 
      Name: !Sub ${StackPrefix}-CodeBuildRole-Arn