AWSTemplateFormatVersion: 2010-09-09
Description: CodeArtifact Template for CloudFormation Demo.
#Metadata: 

Parameters: 
  StackPrefix:
    Description: Stack Resource Name Prefix
    Type: String
    Default: Demo
  DomainName:
    Description: CodeArtifact Domain Name
    Type: String
    Default: my-domain
  RepositoryName:
    Description: CodeArtifact Repository Name
    Type: String
    Default: my-repo

#Mappings: 

#Conditions: 

Resources: 
Resources:
  CodeArtifactDomain:
    Type: 'AWS::CodeArtifact::Domain'
    Properties:
      DomainName: !Ref DomainName
  MavenCentralCodeArtifactRepository:
    Type: 'AWS::CodeArtifact::Repository'
    Properties:
      RepositoryName: maven-central-store
      ExternalConnections:
        - public:maven-central
      DomainName: !GetAtt CodeArtifactDomain.Name
  CodeArtifactRepository:
    Type: 'AWS::CodeArtifact::Repository'
    Properties:
      RepositoryName: !Ref RepositoryName
      DomainName: !GetAtt CodeArtifactDomain.Name
      Upstreams:
        - !GetAtt MavenCentralCodeArtifactRepository.Name

Outputs:
  CodeArtifactDomainName:  
    Description: CodeArtifact Domain Name
    Value: !GetAtt CodeArtifactDomain.Name
    Export: 
      Name: !Sub ${StackPrefix}-CodeArtifactDomainName
  CodeArtifactMavenRepositoryName:
    Description: CodeArtifact Repository Name
    Value: !GetAtt CodeArtifactRepository.Name
    Export:
      Name: !Sub ${StackPrefix}-CodeArtifactRepositoryName
  CodeArtifactMavenRepositoryURL:
    Description: CodeArtifact Repository URL
    Value: !Sub https://${CodeArtifactDomain.Name}-${AWS::AccountId}.d.codeartifact.${AWS::Region}.amazonaws.com/maven/${CodeArtifactRepository.Name}/
    Export: 
      Name: !Sub ${StackPrefix}-CodeArtifactMavenRepositoryURL    
  CodeArtifactRepositoryArn:
    Description: CodeArtifact Repository Arn
    Value: !Ref CodeArtifactRepository  